# Generated by Django 4.0.5 on 2022-12-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeModule', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
