# Generated by Django 4.0.5 on 2022-12-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeModule', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_username',
            field=models.CharField(max_length=150),
        ),
    ]
