# Generated by Django 4.0.5 on 2022-12-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeModule', '0005_alter_userprofile_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postkey',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
