# Generated by Django 4.0.5 on 2023-01-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeModule', '0008_alter_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='False', max_length=1000),
        ),
    ]
