# Generated by Django 4.0.5 on 2022-12-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_rename_receiver_message_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='userkey',
            field=models.CharField(default=0, max_length=1000000),
        ),
    ]
